title: "Nature Kakis Network "
url: https://naturekakis.nparks.gov.sg
favicon: /images/Nature_Kakis_Logo_Full_Colour.png
colors:
  primary-color: "#215732"
  secondary-color: "#244102"
  media-colors:
    - title: media-color-one
      color: "#ffcb00"
    - title: media-color-two
      color: "#7a9a01"
    - title: media-color-three
      color: "#8b572a"
    - title: media-color-four
      color: "#ff9e1b"
    - title: media-color-five
      color: "#af272f"
description: "This website is an Isomer website co-created and co-managed with
  Nature Kakis Youth Stewards. "
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.d9mzm4bflht79.amplifyapp.com
prod: https://master.d9mzm4bflht79.amplifyapp.com
facebook-pixel: ""
shareicon: /images/Nature_Kakis_Logo_Full_Colour.png
is_government: false
google_analytics_ga4: ""
linkedin-insights: ""
resources_name: all
